import { z } from "zod";

export const EquipmentInputModelSchema = z.object({
  Name: z.string(),
  Description: z.string().optional(),
  Manufacturer: z.string().optional(),
  Model: z.string().optional(),
  SerialNumber: z.string().optional(),
  DateInService: z.string().datetime().or(z.string()).optional(),
  WarrantyPartExpDate: z.string().datetime().or(z.string()).optional(),
  WarrantyLaborExpDate: z.string().datetime().or(z.string()).optional(),
  ServiceCategoryIds: z.array(z.number().int()).optional(),
  LocationId: z.number().int().optional(),
  IsDeleted: z.boolean().optional(),
  IsRetired: z.boolean().optional(),
  RetiredDate: z.string().datetime().or(z.string()).optional(),
  SpaceId: z.number().int().optional(),
  EquipmentIdentifier: z.string().optional(),
  DefaultDocumentId: z.number().int().optional(),
  Type: z.number().int().optional(),
  TrackingMetricType: z.number().int().optional(),
  CurrentMileage: z.number().optional(),
  CurrentRuntimeMinutes: z.number().int().optional(),
  LastMetricsUpdate: z.string().datetime().or(z.string()).optional(),
  FuelType: z.number().int().optional(),
  CustomFuel: z.string().optional(),
  UpdateFrequencyType: z.number().int().optional(),
  UpdateFrequencyValue: z.number().int().optional(),
});
