import { z } from "zod";

export const EventCreateModelSchema = z.object({
  EventName: z.string(),
  Description: z.string().optional(),
  SetupStartDate: z.string().datetime().or(z.string()).optional(),
  SetupStartTime: z.string().optional(),
  EventDate: z.string().datetime().or(z.string()),
  StartTime: z.string().optional(),
  EventEndDate: z.string().datetime().or(z.string()).optional(),
  EndTime: z.string().optional(),
  TeardownEndDate: z.string().datetime().or(z.string()).optional(),
  TearDownEndTime: z.string().optional(),
  AdditionalDates: z.array(z.string().datetime().or(z.string())).optional(),
  IsPublic: z.boolean().optional(),
  NumOfPeople: z.number().int().optional(),
  IsAllDayEvent: z.boolean().optional(),
  IsMultiDayEvent: z.boolean().optional(),
  Categories: z.array(z.number().int()).optional(),
  AutoApprove: z.boolean().optional(),
  OwnerId: z.number().int().optional(),
  PublicNotes: z.string().optional(),
  PublicLink: z.string().optional(),
  Locations: z.array(z.number().int()).optional(),
  PublicLocations: z.array(z.number().int()).optional(),
  IsOffSite: z.boolean().optional(),
  OffsiteLocation: z.string().optional(),
  EditorIds: z.array(z.number().int()).optional(),
  ScheduleId: z.number().int().optional(),
  EventId: z.number().int().optional(),
});
