import { z } from "zod";

export const MaintenanceCreateInputModelSchema = z.object({
  ServiceCategoryId: z.number().int(),
  LocationId: z.number().int(),
  MaintenanceType: z.number().int().optional(),
  VendorAssignedId: z.number().int().optional(),
  AssignedVendorContactId: z.number().int().optional(),
  Notes: z.string().optional(),
  StartDate: z.string().datetime().or(z.string()),
  EndDate: z.string().datetime().or(z.string()).optional(),
  Description: z.string(),
  AssignedUserId: z.number().int().optional(),
  AssignedDepartmentId: z.number().int().optional(),
  XDaysAfterGenerated: z.number().int().optional(),
  IsRecurring: z.boolean().optional(),
  XDaysPriorToCreateWo: z.number().int().optional(),
  ReminderType: z.number().int().optional(),
  ReminderInDays: z.number().int().optional(),
  NextReminderDate: z.string().datetime().or(z.string()).optional(),
  ReminderText: z.string().optional(),
  NextScheduledTime: z.string().datetime().or(z.string()).optional(),
  FrequencyTypeId: z.number().int().optional(),
  CustomDates: z.array(z.string().datetime().or(z.string())).optional(),
  GenerateNextDateBasedOnLastCompleted: z.boolean().optional(),
  RequiresApprovalAfterCompletion: z.boolean(),
  PreventNewWoFromBeingCreatedIfPreviousIsNotComplete: z.boolean(),
  StartRunTimeMinutes: z.number().int().optional(),
  ThresholdRunTimeMinutes: z.number().int().optional(),
  RepeatRunTimeMinutes: z.number().int().optional(),
  NextScheduledRunTimeMinutes: z.number().int().optional(),
  StartMileage: z.number().optional(),
  ThresholdMileage: z.number().optional(),
  RepeatMileage: z.number().optional(),
  NextScheduledMileage: z.number().optional(),
});
